<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoaiPhongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('loai_phongs')->delete();
        DB::table('loai_phongs')->insert([
            ['id' => '1','ten_loai_phong'=>'Phòng Standard','dien_tich'=>'20','so_giuong'=>'1', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://plus.unsplash.com/premium_photo-1661964402307-02267d1423f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-door-open me-2"></i> Có các phòng thông nhau</p><p><i class="fa-solid fa-phone-volume me-2"></i> Điện thoại</p><p><i class="fa-solid fa-shirt me-2"></i> Áo choàng tắm</p><p><i class="fa-solid fa-soap me-2"></i> Vật dụng tắm rửa</p><p><i class="fa-solid fa-spray-can-sparkles me-2"></i> Nước hoa</p><p><i class="fa-solid fa-snowflake me-2"></i> Điều hoà</p>' ],
            ['id' => '2','ten_loai_phong'=>'Phòng Superior','dien_tich'=>'25','so_giuong'=>'2', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-shoe-prints me-2"></i> Dép đi trong nhà</p><p><i class="fa-solid fa-bottle-water me-2"></i> Nước uống</p><p><i class="fa-solid fa-martini-glass-citrus me-2"></i> Tủ lạnh nhỏ trong phòng</p><p><i class="fa-solid fa-wifi me-2"></i> Wifi</p><p><i class="fa-solid fa-clock me-2"></i> Đồng hồ báo thức</p><p><i class="fa-solid fa-rug me-2"></i> Thảm</p><p><i class="fa-solid fa-volume-xmark me-2"></i> Cách âm</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p>' ],
            ['id' => '3','ten_loai_phong'=>'Phòng Deluxe','dien_tich'=>'15','so_giuong'=>'2', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>' ],
            ['id' => '4','ten_loai_phong'=>'Phòng Suite','dien_tich'=>'30','so_giuong'=>'1', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>' ],
            ['id' => '5','ten_loai_phong'=>'Phòng View Biển','dien_tich'=>'20','so_giuong'=>'1', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://plus.unsplash.com/premium_photo-1675616563084-63d1f129623d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>' ],
            ['id' => '6','ten_loai_phong'=>'Phòng VIP','dien_tich'=>'22','so_giuong'=>'1', 'so_nguoi_lon'=> rand(1, 5), 'so_tre_em'=> rand(1, 4), 'tinh_trang'=>'1','hinh_anh'=>'https://plus.unsplash.com/premium_photo-1661879252375-7c1db1932572?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-soap me-2"></i> Vật dụng tắm rửa</p><p><i class="fa-solid fa-spray-can-sparkles me-2"></i> Nước hoa</p><p><i class="fa-solid fa-snowflake me-2"></i> Điều hoà</p><p><i class="fa-solid fa-shoe-prints me-2"></i> Dép đi trong nhà</p><p><i class="fa-solid fa-bottle-water me-2"></i> Nước uống</p><p><i class="fa-solid fa-martini-glass-citrus me-2"></i> Tủ lạnh nhỏ trong phòng</p><p><i class="fa-solid fa-wifi me-2"></i> Wifi</p><p><i class="fa-solid fa-clock me-2"></i> Đồng hồ báo thức</p>' ],
        ]);
    }
}
